name: sixten
version: '0.1.0.0'
category: Language
author: Olle Fredriksson
maintainer: fredriksson.olle@gmail.com
copyright: (c) 2014-2017 Olle Fredriksson
license: BSD3
dependencies:
- base >=4.8 && <4.11
library:
  source-dirs: src
executables:
  sixten:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -fwarn-tabs
    - -fwarn-incomplete-record-updates
    - -funbox-strict-fields
    dependencies:
    - ansi-wl-pprint
    - bifunctors
    - bound
    - bytestring
    - containers
    - deriving-compat
    - directory
    - filepath
    - hashable
    - mmorph
    - mtl
    - multiset
    - optparse-applicative
    - parsers
    - process
    - semigroups
    - split
    - temporary
    - text
    - transformers
    - trifecta
    - unordered-containers
    - vector
    - void
data-files:
- rts/forwarddecls.ll
- rts/Builtin1.vix
- rts/Builtin2.vix
